Plugins/BTCPayServer.Plugins.NairaCheckout/ViewModels/MavapayVM/MavapayPayoutViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BTCPayServer.Plugins.NairaCheckout.ViewModels;

public class MavapayPayoutViewModel
{
    public PayoutZARViewModel ZAR { get; set; } = new();
    public PayoutNGNViewModel NGN { get; set; } = new();
    public PayoutKESViewModel KES { get; set; } = new();
    public List<SelectListItem> NGNBanks { get; set; }
    public List<SelectListItem> ZARBanks { get; set; }
    public List<SelectListItem> KESPaymentMethod { get; set; }
}

public class PayoutZARViewModel
{
    public string Bank { get; set; }
    public string AccountNumber { get; set; }
    public string AccountName { get; set; }
    public decimal Amount { get; set; }
}

public class PayoutNGNViewModel
{
    [Required]
    public string BankCode { get; set; }
    [Required]
    public string BankName { get; set; }
    public string AccountNumber { get; set; }

    [Range(4000, double.MaxValue, ErrorMessage = "Amount must be greater than 4000")]
    public decimal Amount { get; set; }
    public string AccountName { get; set; }
}

public class PayoutKESViewModel
{
    public string Method { get; set; }
    public string AccountNumber { get; set; }
    public string AccountName { get; set; }
    public string Identifier { get; set; }
    public decimal Amount { get; set; }
}

public class BankViewModel
{
    public string Code { get; set; }
    public string Name { get; set; }
}

Plugins/BTCPayServer.Plugins.NairaCheckout/Controllers/UINairaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using BTCPayServer.Abstractions.Constants;
using BTCPayServer.Client;
using BTCPayServer.Data;
using BTCPayServer.Data.Payouts.LightningLike;
using BTCPayServer.HostedServices;
using BTCPayServer.Payments;
using BTCPayServer.Payouts;
using BTCPayServer.Plugins.NairaCheckout;
using BTCPayServer.Plugins.NairaCheckout.Data;
using BTCPayServer.Plugins.NairaCheckout.PaymentHandlers;
using BTCPayServer.Plugins.NairaCheckout.Services;
using BTCPayServer.Plugins.NairaCheckout.ViewModels;
using BTCPayServer.Services.Invoices;
using BTCPayServer.Services.Stores;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using NBitcoin;
using NBitcoin.DataEncoders;
using Newtonsoft.Json;

namespace BTCPayServer.Plugins.Template;

[Route("stores/{storeId}/naira")]
[Authorize(AuthenticationSchemes = AuthenticationSchemes.Cookie, Policy = Policies.CanViewProfile)]
public class UINairaController : Controller
{
    private readonly StoreRepository _storeRepository;
    private readonly IHttpClientFactory _clientFactory;
    private readonly InvoiceRepository _invoiceRepository;
    private readonly PaymentMethodHandlerDictionary _handler;
    private readonly NairaStatusProvider _nairaStatusProvider;
    private readonly UserManager<ApplicationUser> _userManager;
    private readonly PullPaymentHostedService _pullPaymentService;
    private readonly GeneralCheckoutService _generalCheckoutService;
    private readonly NairaCheckoutDbContextFactory _dbContextFactory;
    private readonly MavapayApiClientService _mavapayApiClientService;
    public UINairaController
        (StoreRepository storeRepository,
        IHttpClientFactory clientFactory,
        InvoiceRepository invoiceRepository,
        PaymentMethodHandlerDictionary handler,
        NairaStatusProvider nairaStatusProvider,
        UserManager<ApplicationUser> userManager,
        PullPaymentHostedService pullPaymentService,
        GeneralCheckoutService generalCheckoutService,
        MavapayApiClientService mavapayApiClientService,
        NairaCheckoutDbContextFactory dbContextFactory)
    {
        _handler = handler;
        _userManager = userManager;
        _clientFactory = clientFactory;
        _storeRepository = storeRepository;
        _dbContextFactory = dbContextFactory;
        _invoiceRepository = invoiceRepository;
        _pullPaymentService = pullPaymentService;
        _nairaStatusProvider = nairaStatusProvider;
        _generalCheckoutService = generalCheckoutService;
        _mavapayApiClientService = mavapayApiClientService;
    }

    private readonly List<string> lightningPaymentMethods = new List<string> { "BTC-LN" }; // "BTC-LNURL" Mavapay doeas not support LNURL yet
    private StoreData StoreData => HttpContext.GetStoreData();

    [HttpGet]
    public async Task<IActionResult> StoreConfig()
    {
        if (string.IsNullOrEmpty(StoreData.Id))
            return NotFound();

        var paymentMethods = StoreData.GetPaymentMethodConfigs(_handler, onlyEnabled: true);
        var hasLightningPaymentMethod = paymentMethods.Keys.Any(key => lightningPaymentMethods.Contains(key.ToString()));
        await using var ctx = _dbContextFactory.CreateContext();
        var existingSetting = ctx.MavapaySettings.FirstOrDefault(m => m.StoreId == StoreData.Id);
        var model = new NairaStoreViewModel { Enabled = await _nairaStatusProvider.NairaEnabled(StoreData.Id), WebhookSecret = existingSetting?.WebhookSecret, ApiKey = existingSetting?.ApiKey };
        return View(model);
    }


    [HttpPost]
    public async Task<IActionResult> StoreConfig(NairaStoreViewModel viewModel)
    {
        var paymentMethodId = NairaCheckoutPlugin.NairaPmid;
        if (string.IsNullOrEmpty(StoreData.Id))
            return NotFound();

        if (!StoreData.GetPaymentMethodConfigs(_handler, onlyEnabled: true).Keys.Any(k => lightningPaymentMethods.Contains(k.ToString())))
        {
            TempData[WellKnownTempData.ErrorMessage] = "You need to enable lightning payment (BTC-LN) to use this plugin";
            return RedirectToAction(nameof(StoreConfig), new { StoreData.Id, paymentMethodId });
        }

        var blob = StoreData.GetStoreBlob();
        var config = StoreData.GetPaymentMethodConfig<CashPaymentMethodConfig>(paymentMethodId, _handler) ?? new CashPaymentMethodConfig();
        var webhookSecret = !string.IsNullOrEmpty(viewModel.WebhookSecret) ? viewModel.WebhookSecret : Encoders.Base58.EncodeData(RandomUtils.GetBytes(10));
        var webhookUrl = Url.Action(nameof(UINairaPublicController.ReceiveMavapayWebhook), "UINairaPublic", new { storeId = StoreData.Id }, Request.Scheme);

        await using var ctx = _dbContextFactory.CreateContext();
        var apiClient = new MavapayApiClientService(_clientFactory, _dbContextFactory, _invoiceRepository);
        var entity = ctx.NairaCheckoutSettings.FirstOrDefault(c => c.Enabled) ?? new NairaCheckoutSetting { WalletName = Wallet.Mavapay.ToString() };

        bool webhookOk = true;
        if (viewModel.Enabled)
        {
            var existing = ctx.MavapaySettings.FirstOrDefault(m => m.StoreId == StoreData.Id);
            bool needsUpdate = existing == null || existing.WebhookSecret != webhookSecret;
            if (needsUpdate)
                webhookOk = await apiClient.UpdateWebhook(viewModel.ApiKey, webhookUrl, webhookSecret);

            if (!webhookOk)
            {
                TempData[WellKnownTempData.ErrorMessage] = "Cannot connect to Mavapay. Please enter a valid Api Key";
                return RedirectToAction(nameof(StoreConfig), new { StoreData.Id, paymentMethodId });
            }
            if (existing == null)
            {
                ctx.MavapaySettings.Add(new MavapaySetting
                {
                    ApiKey = viewModel.ApiKey,
                    WebhookSecret = webhookSecret,
                    StoreId = StoreData.Id,
                    StoreName = StoreData.StoreName,
                    ApplicationUserId = GetUserId(),
                    IntegratedAt = DateTime.UtcNow
                });
            }
            else
            {
                existing.ApiKey = viewModel.ApiKey;
                existing.WebhookSecret = webhookSecret;
                ctx.MavapaySettings.Update(existing);
            }
        }

        blob.SetExcluded(paymentMethodId, !viewModel.Enabled);
        StoreData.SetPaymentMethodConfig(_handler[paymentMethodId], config);
        StoreData.SetStoreBlob(blob);
        await _storeRepository.UpdateStore(StoreData);

        var checkout = ctx.NairaCheckoutSettings.FirstOrDefault(c => c.Enabled) ?? new NairaCheckoutSetting { WalletName = Wallet.Mavapay.ToString() };
        checkout.Enabled = await _nairaStatusProvider.NairaEnabled(StoreData.Id);

        if (string.IsNullOrEmpty(checkout.Id))
            ctx.NairaCheckoutSettings.Add(checkout);
        else
            ctx.NairaCheckoutSettings.Update(checkout);

        await ctx.SaveChangesAsync();
        return RedirectToAction(nameof(StoreConfig), new { StoreData.Id, paymentMethodId });
    }


    [HttpGet("/mavapay/payout")]
    public async Task<IActionResult> MavapayPayout()
    {
        if (string.IsNullOrEmpty(StoreData.Id))
            return NotFound();

        await using var ctx = _dbContextFactory.CreateContext();
        var mavapaySetting = ctx.MavapaySettings.FirstOrDefault(c => c.StoreId == StoreData.Id);
        var nairaEnabled = await _nairaStatusProvider.NairaEnabled(StoreData.Id);
        var entity = ctx.NairaCheckoutSettings.FirstOrDefault(c => c.Enabled);
        if (mavapaySetting == null || string.IsNullOrEmpty(mavapaySetting.ApiKey) || !nairaEnabled || entity.WalletName != Wallet.Mavapay.ToString())
        {
            TempData[WellKnownTempData.ErrorMessage] = "Kindly activate or configure Mavapay";
            return RedirectToAction(nameof(StoreConfig), new { storeId = StoreData.Id });
        }
        var viewModel = await PayoutViewModel(mavapaySetting);
        return View(viewModel);
    }

    [HttpPost("mavapay/naira/name-enquiry")]
    public async Task<IActionResult> ValidateNgnAccountNumber(MavapayPayoutViewModel model)
    {
        if (string.IsNullOrEmpty(StoreData.Id))
            return NotFound();

        await using var ctx = _dbContextFactory.CreateContext();
        var mavapaySetting = ctx.MavapaySettings.FirstOrDefault(c => c.StoreId == StoreData.Id);
        var viewModel = await PayoutViewModel(mavapaySetting, model);
        if (string.IsNullOrWhiteSpace(model.NGN.AccountNumber) || model.NGN.AccountNumber.Length != 10)
        {
            ModelState.AddModelError("NGN.AccountNumber", "Account number must be exactly 10 digits");
            return View(nameof(MavapayPayout), viewModel);
        }
        var result = await _mavapayApiClientService.NGNNameEnquiry(model.NGN.BankCode, model.NGN.AccountNumber, mavapaySetting.ApiKey);
        if (result == null || string.IsNullOrEmpty(result.accountName))
        {
            ModelState.AddModelError("NGN.AccountNumber", "Account number cannot be verified at the moment");
            return View(nameof(MavapayPayout), viewModel);
        }
        viewModel.NGN.AccountName = result.accountName;
        return View(nameof(MavapayPayout), viewModel);
    }

    [HttpPost("mavapay/ngn-payout")]
    public async Task<IActionResult> ProcessNGNPayout(MavapayPayoutViewModel model)
    {
        if (string.IsNullOrEmpty(StoreData.Id))
            return NotFound();

        await using var ctx = _dbContextFactory.CreateContext();
        var mavapaySetting = ctx.MavapaySettings.FirstOrDefault(c => c.StoreId == StoreData.Id);
        if (string.IsNullOrWhiteSpace(model.NGN.AccountNumber) || model.NGN.AccountNumber.Length != 10)
        {

Plugins/BTCPayServer.Plugins.NairaCheckout/Views/UINaira/ListMavapayPayouts.cshtml
@using BTCPayServer.Abstractions.Contracts
@using BTCPayServer.Abstractions.Extensions
@using BTCPayServer.Plugins.NairaCheckout
@using BTCPayServer.Plugins.NairaCheckout.ViewModels
@using BTCPayServer.Plugins.NairaCheckout.Views
@using Microsoft.AspNetCore.Mvc.TagHelpers
@inject IScopeProvider ScopeProvider
@model PayoutListViewModel
@{
    ViewData.SetActivePage(PluginNavPages.Index, "Mavapay Payout");
    var storeId = ScopeProvider.GetCurrentStoreId();
}

<div class="sticky-header">
    <h2 text-translate="true">@ViewData["Title"]</h2>
    <div class="d-flex gap-3 mt-3 mt-sm-0">
        <a asp-controller="UINaira" asp-action="MavapayPayout" asp-route-storeId="@storeId" class="btn btn-secondary" role="button">Go Back</a>
    </div>
</div>

<partial name="_StatusMessage" />

<form class="d-flex flex-wrap flex-sm-nowrap align-items-center gap-3 mb-4 col-xxl-8" asp-action="ListMavapayPayouts"
      asp-route-storeId="@storeId" method="get">
    <input asp-for="SearchText" class="form-control" name="searchText" placeholder="Search" />
</form>

@if (Model.PayoutTransactions.Any())
{
    <div class="table-responsive-md">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">Pull Payment</th>
                    <th scope="col">External Reference</th>
                    <th scope="col">Amount</th>
                    <th scope="col">Currency</th>
                    <th scope="col">Status</th>
                    <th scope="col" class="text-end"></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var pp in Model.PayoutTransactions)
                {
                    <tr class="mass-action-row">
                        <td>
                            <a 
                                class="link-success text-decoration-none" 
                                asp-controller="UIPullPayment"
                                asp-action="ViewPullPayment"
                                asp-route-pullPaymentId="@pp.PullPaymentId"
                                target="_blank"
                                rel="noopener noreferrer">
								View Pull Payment
                            </a>
                        </td>
                        <td>@pp.ExternalReference</td>
                        <td>@pp.Amount</td>
                        <td>@pp.Currency</td>
                        <td>@(pp.IsSuccess ? "Completed" : "Pending")</td>

                        <td class="text-end">
                            @if (!pp.IsSuccess)
                            {
                                <div class="d-inline-flex align-items-center gap-3">
                                    <a class="link-success text-decoration-none" asp-controller="UINaira" asp-action="VerifyMavapayTransaction"
                                       asp-route-storeId="@storeId" asp-route-externalReferemce="@pp.ExternalReference">Query Transaction Status</a>
                                </div>
                            }
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
}
else
{
    <p class="text-secondary mt-4">
        <span>There are no payout found</span>
    </p>
}

Plugins/BTCPayServer.Plugins.NairaCheckout/Views/UINaira/MavapayPayout.cshtml
@using BTCPayServer.Abstractions.Contracts
@using BTCPayServer.Abstractions.Extensions
@using BTCPayServer.PayoutProcessors
@using BTCPayServer.Payouts
@using BTCPayServer.Plugins.NairaCheckout
@using BTCPayServer.Plugins.NairaCheckout.ViewModels
@using BTCPayServer.Plugins.NairaCheckout.Views
@using Microsoft.AspNetCore.Http
@using Microsoft.AspNetCore.Mvc.TagHelpers
@using Microsoft.AspNetCore.Routing
@inject IEnumerable<IPayoutProcessorFactory> PayoutProcessorFactories
@inject PayoutProcessorService PayoutProcessorService
@inject IHttpContextAccessor HttpContextAccessor
@inject IScopeProvider ScopeProvider
@inject LinkGenerator LinkGenerator
@model MavapayPayoutViewModel
@{
    ViewData.SetActivePage(PluginNavPages.Index, "Mavapay Payout");
    var storeId = ScopeProvider.GetCurrentStoreId();
    PayoutMethodId pmi = PayoutTypes.LN.GetPayoutMethodId("BTC");
    PayoutMethodId pmichain = PayoutTypes.CHAIN.GetPayoutMethodId("BTC");
    string PayoutProcessorLink = LinkGenerator.GetUriByAction(HttpContextAccessor.HttpContext, "ConfigureStorePayoutProcessors", "UIPayoutProcessors", new { StoreId = storeId });
    var fetchProcessors = PayoutProcessorService.GetProcessors(new PayoutProcessorService.PayoutProcessorQuery()
    {
        Stores = new[] { storeId },
        PayoutMethods = new[] { pmi, pmichain }
    });
    var NoPayoutProcessors = PayoutProcessorFactories.Any(factory => factory.GetSupportedPayoutMethods().Contains(pmi)) && (await fetchProcessors).All(data =>
                !new[] { pmi, pmichain }.Contains(data.GetPayoutMethodId()));
}

<div class="sticky-header">
    <h2 text-translate="true">@ViewData["Title"]</h2>
    <div class="d-flex gap-3 mt-3 mt-sm-0">
        <a asp-controller="UINaira" asp-action="ListMavapayPayouts" asp-route-storeId="@storeId" class="btn btn-primary" role="button">View Payouts</a>
    </div>
</div>

@if (NoPayoutProcessors)
{
    <div class="alert alert-warning mb-4" role="alert">
        An automated payout processor is required in order to automate Mavapay payouts. <a class="alert-link p-0" href="@PayoutProcessorLink">Configure now</a>
    </div>
}

<partial name="_StatusMessage" />
<div class="container-fluid px-0">

    <h4 class="mt-4">NGN Payout</h4>
    <form asp-action="ProcessNGNPayout" asp-route-storeId=@storeId method="post">
        <div class="mb-3 w-100 w-md-50">
            <label class="form-label">Bank</label>
            <select asp-items="Model.NGNBanks" asp-for="NGN.BankCode" class="form-select"></select>
        </div>
        <div class="mb-3 w-100 w-md-50">
            <label class="form-label">Account Number</label>
            <div class="input-group">
                <input asp-for="NGN.AccountNumber" class="form-control" maxlength="10" />
                <button type="submit" formaction="@Url.Action("ValidateNgnAccountNumber", "UINaira", new { storeId })" class="btn btn-outline-primary">
                    Validate
                </button>
            </div>
            @if (!string.IsNullOrEmpty(Model.NGN?.AccountName))
            {
                <span class="text-muted">@Model.NGN.AccountName</span>
            }
            <span asp-validation-for="NGN.AccountNumber" class="text-danger"></span>
        </div>
        <div class="mb-3 w-100 w-md-50">
            <label class="form-label">Amount</label>
            <input asp-for="NGN.Amount" type="number" step="1" class="form-control" required />
        </div>

        <button type="submit" class="btn btn-success">Send NGN Payout</button>
    </form>

    <hr class="my-5" />

    <h4 class="mt-4">KES Payout</h4>
    <form asp-action="ProcessKESPayout" asp-route-storeId=@storeId method="post">
        <div class="mb-3 w-100 w-md-50">
            <label class="form-label">Payout Method</label>
            <select asp-items="Model.KESPaymentMethod" asp-for="KES.Method" class="form-select" id="kesMethod"></select>
        </div>
        <div id="kesAccountNumber" class="mb-3 w-100 w-md-50 d-none">
            <label class="form-label">Account Number</label>
            <input asp-for="KES.AccountNumber" class="form-control" />
        </div>
        <div class="mb-3 w-100 w-md-50">
            <label class="form-label">Till/Bill/Phone Number</label>
            <div class="input-group">
                <input asp-for="KES.Identifier" class="form-control" required id="kesIdentifier" />
                <button type="submit" id="validateKesBtn" formaction="@Url.Action("ValidateKesTillAndBillNumber", "UINaira", new { storeId })"
                        class="btn btn-outline-primary d-none">
                    Validate
                </button>
            </div>
            @if (!string.IsNullOrEmpty(Model.KES?.AccountName))
            {
                <span class="text-muted">@Model.KES.AccountName</span>
                <input type="hidden" asp-for="KES.AccountName" />
            }
            <span id="kesValidationResult" class="text-muted"></span>
            <span asp-validation-for="KES.Identifier" class="text-danger"></span>
        </div>
        <div class="mb-3 w-100 w-md-50">
            <label class="form-label">Amount</label>
            <input asp-for="KES.Amount" type="number" step="1" class="form-control" required />
        </div>

        <button type="submit" class="btn btn-success">Send KES Payout</button>
    </form>

    <hr class="my-5" />

    <h4 class="mt-4">ZAR Payout</h4>
    <form asp-action="ProcessZARPayout" asp-route-storeId=@storeId method="post">
        <div class="mb-3 w-100 w-md-50">
            <label class="form-label">Bank</label>
            <select asp-items="Model.ZARBanks" asp-for="ZAR.Bank" class="form-select"></select>
        </div>
        <div class="mb-3 w-100 w-md-50">
            <label class="form-label">Account Name</label>
            <input asp-for="ZAR.AccountName" class="form-control" required />
        </div>
        <div class="mb-3 w-100 w-md-50">
            <label class="form-label">Bank Account Number</label>
            <input asp-for="ZAR.AccountNumber" class="form-control" required />
        </div>
        <div class="mb-3 w-100 w-md-50">
            <label class="form-label">Amount</label>
            <input asp-for="ZAR.Amount" type="number" step="1" class="form-control" required />
        </div>

        <button type="submit" class="btn btn-primary">Send ZAR Payout</button>
    </form>
</div>




@section PageFootContent {
    <script>
        document.addEventListener("DOMContentLoaded", function () {
            const methodSelect = document.getElementById("kesMethod");
            const accountNumberDiv = document.getElementById("kesAccountNumber");

            const validateBtn = document.getElementById("validateKesBtn");
            const identifierInput = document.getElementById("kesIdentifier");

            function toggleUI() {
                const method = methodSelect.value;

                if (method === "BillNumber") {
                    accountNumberDiv.classList.remove("d-none");
                    accountNumberDiv.querySelector("input").setAttribute("required", "required");
                } else {
                    accountNumberDiv.classList.add("d-none");
                    accountNumberDiv.querySelector("input").removeAttribute("required");
                }

                if (method === "TillNumber" || method === "BillNumber") {
                    validateBtn.classList.remove("d-none");
                } else {
                    validateBtn.classList.add("d-none");
                }
            }
            methodSelect.addEventListener("change", toggleUI);
            toggleUI();
        });
    </script>
}